
#Common only settings for Abnormals Core, this will affect all depending mods
[common]
	#If Quark Sign Editing should be enabled; Default: True
	quarkSignEditing = true
	#If Quark Sign Editing requires an empty hand to edit; Default: False
	signEditingRequiresEmptyHand = false

