
[Time]
	#The ticks of drying per item outdoors. (1 second = 20 ticks)
	#Range: > 200
	OutdoorDryingBasic = 800
	#The ticks of drying per item indoors. (1 second = 20 ticks)
	#Range: > 200
	IndoorDryingBasic = 900
	#The ticks of fermentation per item. (1 second = 20 ticks)
	#Range: > 200
	FermentationBasic = 1000
	#The ticks of baking per item. (1 second = 20 ticks)
	#Range: > 200
	BakeBasic = 300

[Blocks]
	#The capacity of wooden barrel. (mB)
	#Range: > 100
	WoodenBarrelCapacity = 4000
	#The capacity of drink maker. (mB)
	#Range: > 100
	DrinkMakerCapacity = 2000

[HUD]
	#The position X of Player Temperature HUD
	#Range: > -2147483648
	PlayerTemperatureX = 10
	#The position Y of Player Temperature HUD
	#Range: > -2147483648
	PlayerTemperatureY = 40

[Others]
	#Can bone meal be used to grow crops?
	BoneMeal = false
	#Can ash be used as bone meal?
	Ash = true

