
["Feature Options"]

	["Feature Options".Dungeons]
		#
		# Add the custom dungeons to modded biomes of the same categories/type.
		addDungeonsToModdedBiomes = false
		#
		# How often dungeons will attempt to spawn per chunk.
		# 1 for extremely rare Dungeons and 1000 for max Dungeon spawnrate.
		#Range: 1 ~ 1000
		dungeonSpawnrate = 8
		#
		# Replace vanilla dungeon in Badlands biomes with Badlands themed dungeon.
		badlandsDungeons = true
		#
		# Replace vanilla dungeon in Dark Forest biomes with Dark Forest themed dungeon.
		darkForestDungeons = true
		#
		# Replace vanilla dungeon in Desert biomes with Desert themed dungeon.
		desertDungeons = true
		#
		# Replace vanilla dungeon in Jungle biomes with Jungle themed dungeon.
		jungleDungeons = true
		#
		# Replace vanilla dungeon in Mushroom biomes with Mushroom themed dungeon.
		mushroomDungeons = true
		#
		# Replace vanilla dungeon in icy/snow biomes with icy/snow themed dungeon.
		snowDungeons = true
		#
		# Replace vanilla dungeon in Swamp biomes with Swamp themed dungeon.
		swampDungeons = true
		#
		# Add End themed dungeon to End biomes outside the Enderdragon island.
		endDungeons = true
		#
		# Add Nether themed dungeon to Nether biomes.
		netherDungeons = true
		#
		# Add ocean themed dungeon to ocean biomes. These will spawn on
		# the ocean's floor and inside water filled caves and ravines.
		#
		# Note: Vanilla Dungeons will still generate if biome has them
		# which is unlike the other modded dungeons from this mod which
		# replace the Vanilla Dungeons.
		oceanDungeons = true

	["Feature Options"."Small Wells"]
		#
		# Add the custom wells to modded biomes of the same categories/type.
		addWellsToModdedBiomes = false
		#
		# How often wells will attempt to spawn per chunk.
		# The chance of a well generating at a chunk is 1/spawnrate.
		# 1 for wells spawning in every chunk and 10000 for extremely rare wells.
		#Range: 1 ~ 10000
		wellSpawnrate = 350
		#
		# Determines if Wells can have a chance of spawning a Bell.
		canHaveBells = true
		#
		# Add Badlands themed wells to Badlands biomes.
		badlandsWells = true
		#
		# Add Nether themed wells to Nether biomes.
		netherWells = true
		#
		# Add Snow themed wells to snowy and icy biomes.
		snowWells = true
		#
		# Add mossy stone themed wells to Jungles, Dark Oak, and Swamp biomes.
		mossyStoneWells = true
		#
		# Add a wood themed wells to Forest and Birch Forest biomes.
		forestWells = true

	["Feature Options".Misc]
		#
		# Add the custom features to modded biomes of the same categories/type.
		addMiscToModdedBiomes = false
		#
		# Adds tiny boulders to Taiga Mountains and Snowy Taiga Mountains biomes 
		# that can contain small amounts of Coal and Iron ores.
		boulderTiny = true
		#
		# Replaces boulders in Giant Tree Taiga Hills and Giant Spruce Taiga Hills
		# biomes with a larger boulder that can contain Coal, Iron, and extremely
		# rarely, can also have Diamond Ores.
		boulderGiant = true
		#
		# Adds a large tree somewhat uncommonly to Swamp biome and replaces
		# all vanilla trees in Swamp Hills biome with the larger tree.
		hornedSwampTree = true

["Structure Options"]

	["Structure Options".Mineshaft]
		#
		# How often Mineshafts will spawn.
		# 0 for no Mineshafts and 1000 for max spawnrate.
		#Range: 0 ~ 1000
		mineshaftSpawnrate = 40
		#
		# Controls whether loot chests spawn or not in modded Mineshafts.
		lootChestsMS = true
		#
		# Add the custom Mineshafts to modded biomes of the same categories/type.
		addMineshaftsToModdedBiomes = false
		#
		# Replace Mineshafts in Birch biomes with a Birch themed Mineshaft.
		birchMineshafts = true
		#
		# Replace Mineshafts in Jungle biomes with a Jungle themed Mineshaft.
		jungleMineshafts = true
		#
		# Replace Mineshafts in Desert biomes with a Desert themed Mineshaft.
		desertMineshafts = true
		#
		# Replace Mineshafts in Mountain (Extreme Hills) biomes with a Stone themed Mineshaft.
		stoneMineshafts = true
		#
		# Replace Mineshafts in Savanna biomes with a Savanna themed Mineshaft.
		savannaMineshafts = true
		#
		# Replace Mineshafts in Snowy/Icy biomes with an Ice themed Mineshaft.
		# Note: Snowy Taiga Biomes will get Ice Mineshaft instead of Taiga theme.
		icyMineshafts = true
		#
		# Replace Mineshafts in Ocean biomes with an Ocean themed Mineshaft.
		oceanMineshafts = true
		#
		# Replace Mineshafts in Taiga biomes with a Taiga themed Mineshaft.
		taigaMineshafts = true
		#
		# Replace Mineshafts in Swamps and Dark Forests with a
		# swampy/dark oak themed Mineshaft.
		swampAndDarkForestMineshafts = true
		#
		# Add End themed Mineshafts to End biomes outside the Enderdragon island.
		endMineshafts = true
		#
		# Add Nether themed Mineshafts to Nether biomes.
		netherMineshafts = true

	["Structure Options".Stronghold]
		#
		# Use vanilla Stronghold instead of using this mod's modded version.
		# Note: The other Stronghold configs here will have no effect on vanilla Strongholds. 
		# WARNING: Nether Strongholds will be turned off too when this option is on.
		useVanillaStronghold = false
		#
		# Allow Stonebrick styled Stronghold to generate in non-Nether biomes.
		allowStonebrickStronghold = true
		#
		# Allow Nether-styled Strongholds to spawn in Nether category biomes.
		# Note: Eyes of Ender will work and show the closest Nether Stronghold too.
		allowNetherStronghold = true
		#
		# How rare are Strongholds.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		strongholdSpawnrate = 85
		#
		# How often Silverfish Blocks will generate in Strongholds as a percentage.
		# Note: Mossy Stone Bricks block cannot be infected by Silverfish
		# 0 for no Silverfish Blocks and 100 for max spawnrate.
		#Range: 0.0 ~ 100.0
		silverfishSpawnrateSH = 0.8
		#
		# Make Mob Spawners generate in rooms other than the Portal Room in Strongholds.
		# Note: Spawners in Portal Room will always remain.
		allowExtraSpawnersSH = true
		#
		# How large the Stronghold is on average as a percentage.
		# Note: The Stonghold is much larger by default. To get something 
		# closer to vanilla stronghold size, use the value of 60.
		# 10 for supertiny Strongholds and 2000 for supermassive Strongholds.
		#Range: 10.0 ~ 2000.0
		strongholdSizeSH = 100.0
		#
		# Controls whether loot chests spawn or not in the Stronghold.
		lootChestsSH = true

	["Structure Options"."Jungle Fortress"]
		#
		# How rare are Jungle Fortresses.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		jungleFortressSpawnrate = 32
		#
		# How often Silverfish Blocks will generate in Jungle Fortress as a percentage.
		# Note: Mossy Stone Bricks block cannot be infected by Silverfish
		# 0 for no Silverfish Blocks and 100 for max spawnrate.
		#Range: 0.0 ~ 100.0
		silverfishSpawnrateJF = 0.5
		#
		# Silverfish Mob Spawners generate in Stone Fortresses.
		# If turned off, the spawners will become Skeleton spawners.
		allowSilverfishSpawnerJF = true
		#
		# Controls whether loot chests spawn or not in Jungle Fortresses.
		lootChestsJF = true
		#
		# Add Jungle Fortress to modded jungle biomes.
		addJungleFortressToModdedBiomes = false

	["Structure Options"."Nether Temple"]
		#
		# How rare are Nether Temples in Nether.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		netherTempleSpawnrate = 20
		#
		# Controls whether loot chests spawn or not in Nether Temples.
		lootChestsNT = true
		#
		# Add Jungle Fortress to modded jungle biomes.
		addNetherTempleToModdedBiomes = false

	["Structure Options"."Badlands Temple"]
		#
		# How rare are Nether Temples in Nether.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		badlandsTempleSpawnrate = 20
		#
		# Controls whether loot chests spawn or not in Badlands Temples.
		lootChestsBT = true
		#
		# Add Jungle Fortress to modded jungle biomes.
		addBadlandsTempleToModdedBiomes = false

	["Structure Options".Igloos]
		#
		# How rare are Grassy Igloos in Plains and Forests.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		grassyIglooSpawnrate = 20
		#
		# Add Grassy Igloos to modded biomes that are
		# most likely grassy fields or temperate forests.
		addGrassyIglooToModdedBiomes = false
		#
		# How rare are Stone Igloos in Giant Tree Taiga biomes.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		stoneIglooSpawnrate = 20
		#
		# Add Stone Igloos to modded biomes that are
		# most likely Giant Tree Taiga variants.
		addStoneIglooToModdedBiomes = false

